# Generated by Django 5.1.2 on 2024-10-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('first_name', models.CharField(max_length=122)),
                ('last_name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=130)),
                ('address', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=122)),
                ('mobile_number', models.IntegerField(max_length=12)),
                ('message', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
