# Generated by Django 5.1.2 on 2024-10-12 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='serial_number',
        ),
    ]
